apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: us-central1-docker.pkg.dev/PROJECT_ID/repo/demo-repository/fastapi:latest
          ports:
            - containerPort: 8000